### ISSUE TITLE
Questions about adding a custom Sketchpad component

### ISSUE THREAD

**Issue by KevinBusch** [AndcultureCode/AndcultureCode.JavaScript.React.Components#42]
Where does the sketchpad component belong in this folder structure?  I'm assuming this is considered an atom or is it considered molecule?  How do we differentiate the two?  The current sketchpad component is rendering a `<div/>` with two containing `<canvas/>` elements.  I'm also assuming this would be considered a form component and therefore belong in a/the forms folder?

**Comment by KevinBusch** [comment]
Also, what's the folder structuring convention for our react components?  The current components within the existing forms folder are all thrown together with their associated tests and storybook files.  The new sketch component I'm adding has a lot of files to it.  For now, I'm going to create a folder for all it's contents to avoid cluttering the existing forms folder...

**Comment by wintondeshong** [comment]
Sure! If you haven't already, it would help to read up on the frontend architecture resources found in the boilerplate's documentation [found here](https://github.com/AndcultureCode/AndcultureCode.DotnetReact.Boilerplate/blob/master/documentation/frontend-architecture.md). This will help you understand some of the rules/thinking around atomic component design.

Without seeing the code, per your description it does sound like it will be an atom. As for sub-folder, while sketchpad might be used in forms at times, it does seem like a component that could be used in various contexts. I'd just put the component, tests and stories in a 'sketchpad' folder. 

Beyond all that, we can review when its time for PR. Its possible we might further identify utilities, sub components, etc... that could use abstraction within this and to other packages (ie. Core or React).

Hope that helps!

**Comment by brandongregoryscott** [comment]
Published with [v0.3.0](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React.Components/releases/tag/v0.3.0)
