### ISSUE TITLE
Merge DragAndDropListBox into ListBox

### ISSUE THREAD

**Issue by alexgetty** [AndcultureCode/AndcultureCode.JavaScript.React.Components#95]
In an effort to reduce duplicate components with variant functionality, I think that the drag and drop functionality should be broken out into a reusable utility/component, then add an 'isDraggable' boolean prop to the `ListBox` component.

**Comment by brandongregoryscott** [comment]
Responding similarly to #90 - my hesitation for this, again, would just be growing logic that would live inside `ListBox` to accommodate drag & drop. This feels like a separate component just like it would feel like a separate function if `isDraggable` was a regular argument - see https://github.com/AndcultureCode/AndcultureCode/blob/main/clean-code/FUNCTIONS.md#do-one-thing as an example. Perhaps it can be done with minor duplication/overhead, but I'm not sure it's a big deal to keep broken out.

**Comment by alexgetty** [comment]
Is there a way we can abstract drag and drop functionality into a higher-order component so it can be reused across many different components without growing the complexity of them? I don't have much experience with that so I'm not sure if it would be an appropriate solution in this case.

**Comment by brandongregoryscott** [comment]
Closing this as we have since removed both components from the package
